YAPP-Github/20th-iOS-Team-1-FE

- App/App.xcodeproj/project.pbxproj
- App/App/Sources/Common/Coordinator/AppCoordinator.swift
- App/App/Sources/Common/View/BorderButton.swift
- App/App/Sources/Scenes/AuthScene/Entity/UserAuthentification.swift
- App/App/Sources/Scenes/AuthScene/SignUpInfomationScene/SignUpInfomationCoordinator.swift
- App/App/Sources/Scenes/AuthScene/SignUpInfomationScene/SignUpInfomationReactor.swift
- App/App/Sources/Scenes/AuthScene/SignUpInfomationScene/SignUpInfomationViewController.swift
- App/App/Sources/Scenes/AuthScene/SignUpProfileScene/SignUpProfileCoordinator.swift
- App/App/Sources/Scenes/AuthScene/SignUpProfileScene/SignUpProfileReactor.swift
작업 내용 💾
관련 이슈 🔗
https://github.com/YAPP-Github/20th-iOS-Team-1-FE/issues/27
리뷰어분들께 💚
> [feat] 나이, 성별 체크 화면 추가

- App/App.xcodeproj/project.pbxproj
- App/App/Sources/Common/Repository/AppleLoginRepository.swift
- App/App/Sources/Common/Service/Network/DTO/AppleCredentialRequestDTO.swift
- App/App/Sources/Common/Service/Network/Network/NetworkManager.swift
- App/App/Sources/Scenes/AuthScene/LoginScene/LoginCoordinator.swift
- App/App/Sources/Scenes/AuthScene/LoginScene/LoginReactor.swift
- App/App/Sources/Scenes/AuthScene/SignUpAreaScene/Area.swift
- App/App/Sources/Scenes/AuthScene/SignUpAreaScene/SignUpAreaCoordinator.swift
- App/App/Sources/Scenes/AuthScene/SignUpAreaScene/SignUpAreaReactor.swift
- App/App/Sources/Scenes/AuthScene/SignUpAreaScene/SignUpAreaViewController.swift
- App/App/Sources/Scenes/AuthScene/SignUpInfomationScene/SignUpInfomationCoordinator.swift
- App/App/Sources/Scenes/AuthScene/SignUpInfomationScene/SignUpInfomationReactor.swift
작업 내용 💾
관련 이슈 🔗
https://github.com/YAPP-Github/20th-iOS-Team-1-FE/issues/24
https://github.com/YAPP-Github/20th-iOS-Team-1-FE/issues/15
리뷰어분들께 💚
코디네이터 버그로 인해 화면 전환 매우 이상함
활동 지역 화면 resignFirstResponder 미구현
애플로그인
애플재로그인 ( 자동로그인 X)
> [Feature] 애플로그인 구현 

- App/App.xcodeproj/project.pbxproj
- App/App.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- App/App/Sources/Common/Coordinator/AppCoordinator.swift
- App/App/Sources/Common/Coordinator/AuthCoordinator.swift
- App/App/Sources/Common/Coordinator/Protocol/SceneCoordinator.swift
- App/App/Sources/Common/Coordinator/TabCoordinator.swift
- App/App/Sources/Common/Repository/AccountValidationRepository.swift
- App/App/Sources/Common/Repository/SignUpRepository.swift
- App/App/Sources/Common/UseCase/KeychainUseCase.swift
- App/App/Sources/Extension/String+Extension.swift
- App/App/Sources/Scenes/AuthScene/Entity/UserAccount.swift
- App/App/Sources/Scenes/AuthScene/SignUpAreaScene/SignUpAreaReactor.swift
- App/App/Sources/Scenes/AuthScene/SignUpAreaScene/SignUpAreaViewController.swift
- App/App/Sources/Scenes/ChattingScene/ChattingCoordinator.swift
- App/App/Sources/Scenes/GatherListScene/GatherListCoordinator.swift
- App/App/Sources/Scenes/ProfileScene/MainScene/ProfileCoordinator.swift
- App/App/Sources/Scenes/SearchScene/SearchCoordinator.swift
https://github.com/YAPP-Github/20th-iOS-Team-1-FE/issues/30
일단 마지막 화면 대도시는 서울만 선택해주세요
소도시가 자동으로 종로구로 결정되도록 일단 처리했습니다.
현재 서버측에러 500이 뜨니까 클라이언트 코드에는 문제가 없어보입니다.
> [Feature] Auth - 인증 파이프라인

- App/App.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- App/App/Sources/Common/Coordinator/AppCoordinator.swift
- App/App/Sources/Common/Repository/GatherRepository.swift
- App/App/Sources/Extension/UIImage+Extension.swift
- App/App/Sources/Scenes/SearchScene/Entity/GatherCategory.swift
- App/App/Sources/Scenes/SearchScene/Entity/GatherConfigurationForAnnotation.swift
- App/App/Sources/Scenes/SearchScene/SearchViewController.swift
> [Feature] 서버로부터 받아온 Annotation을 통해 Pin 표시

- App/App.xcodeproj/project.pbxproj
- App/App/Sources/Common/View/Divider.swift
- App/App/Sources/Scenes/GatherListScene/DetailGatherScene/DetailGatherReactor.swift
- App/App/Sources/Scenes/GatherListScene/DetailGatherScene/DetailGatherViewController.swift
> [feat] DetailGather 일부 구현

- App/App.xcodeproj/project.pbxproj
- App/App/Sources/Common/Repository/GatherRepository.swift
- App/App/Sources/Scenes/SearchScene/Entity/GatherCategory.swift
- App/App/Sources/Scenes/SearchScene/Entity/GatherConfigurationForSheet.swift
- App/App/Sources/Scenes/SearchScene/MapViewBottomSheetContentView.swift
- App/App/Sources/Scenes/SearchScene/SearchReactor.swift
- App/App/Sources/Scenes/SearchScene/SearchViewController.swift
#48 
BottomSheetResponseDTO 안만들고 그냥 화면에 그려보려다가 코드가 너무 엉망이 되서 DTO 따로 만들어서  진행해야할 것 같습니다.  강아지 크기든, 성별이든 상황에 따라 UI 내용이 달라져서요..
> [Feature] Search - BottomSheet UI 진행 중

- App/App/Resources/Assets.xcassets/Color/subGreen.colorset/Contents.json
- App/App/Sources/Common/View/TagCollectionViewCell.swift
- App/App/Sources/Extension/UIColor+Extension.swift
- App/App/Sources/Scenes/ProfileScene/MainScene/ProfileViewController.swift
- App/App/Sources/Scenes/ProfileScene/MainScene/SubComponents/InitialIntroductionView.swift
- App/App/Sources/Scenes/ProfileScene/MainScene/SubComponents/IntroduceView.swift
> [Feature] 마이페이지 - 색상 관련 수정

- App/App.xcodeproj/project.pbxproj
- App/App.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- App/App/Sources/Common/Repository/GatherRepository.swift
- App/App/Sources/Common/Service/Network/DTO/GatherConfigurationForSheetResponseDTO.swift
- App/App/Sources/Scenes/SearchScene/Entity/ClubStatus.swift
- App/App/Sources/Scenes/SearchScene/Entity/GatherConfigurationForSheet.swift
- App/App/Sources/Scenes/SearchScene/Entity/OwnerSex.swift
- App/App/Sources/Scenes/SearchScene/Entity/PetSizeType.swift
- App/App/Sources/Scenes/SearchScene/MapViewBottomSheetContentView.swift
- App/App/Sources/Scenes/SearchScene/SearchReactor.swift
- App/App/Sources/Scenes/SearchScene/SearchViewController.swift
close #48 
야밤에 여러분들에게 혼란을 드려서 너무 죄송합니다.. 리베이스 과정에서 뭔가 꼬였는지 제 머리가 꼬였는지 죄송합니다.. 
다음에는 이런 일 없도록 하겠습니다.
강아지 종류와, 크기가 선택되지 않는 경우는 고려하지 않았습니다.
> [feat] AnnotationView 선택 시 BottomSheet 호출

- App/App.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- App/App/Sources/Common/Coordinator/AppCoordinator.swift
- App/App/Sources/Common/Repository/SignUpRepository.swift
- App/App/Sources/Common/Service/Network/Network/NetworkManager.swift
- App/App/Sources/Scenes/AuthScene/SignUpAgreementScene/SignUpAgreementViewController.swift
- App/App/Sources/Scenes/AuthScene/SignUpProfileScene/SignUpProfileViewController.swift
- App/App/Sources/Scenes/GatherListScene/DetailGatherScene/DetailGatherReactor.swift
- App/App/Sources/Scenes/GatherListScene/DetailGatherScene/DetailGatherViewController.swift
https://github.com/YAPP-Github/20th-iOS-Team-1-FE/issues/51
> [Feature] DetailGather - 레이아웃 잡기

- App/App.xcodeproj/project.pbxproj
- App/App/Sources/Extension/MKMapView+Extension.swift
- App/App/Sources/Extension/UIImage+Extension.swift
- App/App/Sources/Extension/UILabel+Extension.swift
- App/App/Sources/Scenes/SearchScene/SearchViewController.swift
주소를 많이 요청하면 서버가 nil을 반환하더라고요.. 일단 쓰로틀 2초로 해서 요청중입니다.
> [feat] 모임 생성 화면 중 위치 설정 부분 UI 구성

- App/App.xcodeproj/project.pbxproj
- App/App/Sources/Common/Repository/SignUpRepository.swift
- App/App/Sources/Extension/UIImageView+Extension.swift
- App/App/Sources/Scenes/AuthScene/SignUpAreaScene/SignUpAreaReactor.swift
> [feat] 회원가입 multipart/form-data 통신

- App/App.xcodeproj/project.pbxproj
- App/App/Sources/Common/Repository/SignUpRepository.swift
- App/App/Sources/Extension/NSMutableData+Extension.swift
- App/App/Sources/Extension/UIImageView+Extension.swift
- App/App/Sources/Scenes/AuthScene/SignUpAreaScene/SignUpAreaReactor.swift
> [feat] NSMutableData Extension 추가

- App/App/Sources/Application/AppDelegate.swift
- App/App/Sources/Application/SceneDelegate.swift
- App/App/Sources/Common/Coordinator/AppCoordinator.swift
- App/App/Sources/Common/Repository/ProfileRespository.swift
- App/App/Sources/Common/Service/Network/APIConstants.swift
- App/App/Sources/Scenes/ProfileScene/MainScene/ProfileCoordinator.swift
- App/App/Sources/Scenes/ProfileScene/MainScene/ProfileMainRepositoryInterface.swift
- App/App/Sources/Scenes/ProfileScene/MainScene/ProfileReactor.swift
https://github.com/YAPP-Github/20th-iOS-Team-1-FE/issues/10
마이페이지 조회와 동일한 로직으로 자동로그인 여부 결정
현재 마이페이지 조회 변경안되어있음, 선반영
현재 회원가입할때 400에러 뜨고있음. 확인필요
> [Feature] 공통 - 자동로그인

- App/App/Sources/Common/Repository/GatherRepository.swift
- App/App/Sources/Common/Service/Network/APIConstants.swift
- App/App/Sources/Scenes/SearchScene/SearchCoordinator.swift
- App/App/Sources/Scenes/SearchScene/SearchGatherScene/SearchGatherReactor.swift
- App/App/Sources/Scenes/SearchScene/SearchGatherScene/SearchGatherViewController.swift
- App/App/Sources/Scenes/SearchScene/SearchGatherScene/View/CategorySelectButtonView.swift
카테고리 요청 완료 후 맵 화면으로 검색 결과 가져오는 법 고민 중
> [Feature] Search - 검색어 요청 구현

- App/App.xcodeproj/project.pbxproj
- App/App/Sources/Application/AppDelegate.swift
- App/App/Sources/Application/SceneDelegate.swift
- App/App/Sources/Common/Coordinator/AppCoordinator.swift
- App/App/Sources/Common/Coordinator/TabCoordinator.swift
- App/App/Sources/Common/Repository/CommentRepository.swift
- App/App/Sources/Common/Repository/GatherListRepository.swift
- App/App/Sources/Common/Service/Keychain/KeychainProvider/KeychainAccount.swift
- App/App/Sources/Common/Service/Network/APIConstants.swift
- App/App/Sources/Common/Service/Network/DTO/ClubInfosResponseDTO.swift
- App/App/Sources/Common/Service/Network/DTO/ContentResponseDTO.swift
- App/App/Sources/Common/Service/Network/DTO/GatherListResponseDTO.swift
- App/App/Sources/Scenes/AuthScene/AuthCoordinator.swift
- App/App/Sources/Scenes/AuthScene/Entity/Authentification.swift
- App/App/Sources/Scenes/AuthScene/LoginScene/LoginReactor.swift
- App/App/Sources/Scenes/AuthScene/SignUpAreaScene/SignUpAreaViewController.swift
- App/App/Sources/Scenes/AuthScene/SignUpPrivacyPolicyScene/SignUpPrivacyPolicyViewController.swift
- App/App/Sources/Scenes/GatherScene/DetailGatherScene/CommentRepositoryInterface.swift
- App/App/Sources/Scenes/GatherScene/GatherListScene/GatherListCoordinator.swift
- App/App/Sources/Scenes/GatherScene/GatherListScene/GatherListReactor.swift
- App/App/Sources/Scenes/GatherScene/GatherListScene/GatherListRepositoryInterface.swift
> [Feature] 모임 / 인증

- App/App.xcodeproj/project.pbxproj
- App/App/Sources/Common/Repository/EditProfileRepository.swift
- App/App/Sources/Scenes/ProfileScene/EditProfileScene/EditProfileViewController.swift
- App/App/Sources/Scenes/ProfileScene/EditProfileScene/EditProflieReactor.swift
- App/App/Sources/Scenes/ProfileScene/MainScene/ProfileReactor.swift
- App/App/Sources/Scenes/ProfileScene/MainScene/ProfileViewController.swift
- App/App/Sources/Scenes/ProfileScene/MainScene/View/IntroduceView.swift
- App/App/Sources/Scenes/ProfileScene/MainScene/View/ProfileContentView.swift
- App/App/Sources/Scenes/ProfileScene/ProfileCoordinator.swift
https://github.com/YAPP-Github/20th-iOS-Team-1-FE/issues/78
프로필 후딱 끝내고 모임 들가겠습니다,, 생각보다 늦어지네요 😢
> [feat] 자기소개 수정 API 연동

- App/App.xcodeproj/project.pbxproj
- App/App/Sources/Common/Repository/CreateGatherRepository.swift
- App/App/Sources/Common/View/DatePicker.swift
- App/App/Sources/Scenes/BreedSelectScene/SearchBreedViewController.swift
- App/App/Sources/Scenes/CreateGatherScene/CreateGatherReactor.swift
- App/App/Sources/Scenes/CreateGatherScene/CreateGatherRepositoryInterface.swift
- App/App/Sources/Scenes/CreateGatherScene/CreateGatherViewController.swift
- App/App/Sources/Scenes/CreateGatherScene/View/CreateGatherView.swift
- App/App/Sources/Scenes/ProfileScene/AddPetScene/AddPetViewController.swift
- App/App/Sources/Scenes/SearchScene/SearchCoordinator.swift
- App/App/Sources/Scenes/SearchScene/SearchReactor.swift
- App/App/Sources/Scenes/SearchScene/SearchViewController.swift
> [Feature] 모임 생성 UI 완료

- App/App/Sources/Common/Service/Network/DTO/Club/CreateClubRequestDTO.swift
- App/App/Sources/Scenes/CreateGatherScene/CreateGatherReactor.swift
> [feat] 모임 생성 api 수정, 조건 수정

- App/App/Sources/Common/Repository/EditProfileRepository.swift
- App/App/Sources/Common/Repository/ProfileRespository.swift
- App/App/Sources/Common/Service/Network/APIConstants.swift
- App/App/Sources/Scenes/GatherScene/GatherListScene/GatherListCoordinator.swift
- App/App/Sources/Scenes/ProfileScene/MainScene/ProfileMainRepositoryInterface.swift
- App/App/Sources/Scenes/ProfileScene/MainScene/ProfileReactor.swift
- App/App/Sources/Scenes/ProfileScene/MainScene/ProfileViewController.swift
- App/App/Sources/Scenes/ProfileScene/ProfileCoordinator.swift
탈퇴 테스트하다가 다시 가입 안되는중 ,, 애플로긴 토큰 이슈 해결해보려다 실패ㅐㅐㅐㅐ
> [feat] 탈퇴, 로그아웃 네트워크 연동

- App/App.xcodeproj/project.pbxproj
- App/App/Resources/Assets.xcassets/Color/tagLine.colorset/Contents.json
- App/App/Sources/Common/Repository/DetailGatherRepository.swift
- App/App/Sources/Common/Service/Network/DTO/Club/ParticipateDTO.swift
- App/App/Sources/Extension/String+Extension.swift
- App/App/Sources/Extension/UILabel+Extension.swift
- App/App/Sources/Scenes/GatherScene/DetailGatherScene/CommentCell.swift
- App/App/Sources/Scenes/GatherScene/DetailGatherScene/DetailGatherReactor.swift
- App/App/Sources/Scenes/GatherScene/DetailGatherScene/DetailGatherRepositoryInterface.swift
- App/App/Sources/Scenes/GatherScene/DetailGatherScene/DetailGatherViewController.swift
- App/App/Sources/Scenes/ProfileScene/AddPetScene/AddPetReactor.swift
- App/App/Sources/Scenes/ProfileScene/MainScene/ProfileReactor.swift
- App/App/Sources/Scenes/SearchScene/SearchViewController.swift
> [Hotfix] 1.0.2 버그 수정
